import json
import os
import time
from datetime import datetime
from random import random

from confluent_kafka import Producer
# from pydantic import BaseModel
from backend.libs.common.telemetry_models import TelemetryPoint  # via PYTHONPATH
from prometheus_client import Counter, start_http_server

# --- Config ------------------------------------------------------------------

KAFKA_BROKER = os.getenv("KAFKA_BROKER", "kafka:9092")
TELEMETRY_TOPIC = os.getenv("TELEMETRY_TOPIC", "telemetry.raw")
METRICS_PORT = int(os.getenv("METRICS_PORT", "8001"))

# --- Prometheus Metrics ------------------------------------------------------

TELEMETRY_GENERATED = Counter(
    "telemetry_generated_total",
    "Total number of telemetry messages generated by ingest-service",
)

TELEMETRY_DELIVERY_SUCCESS = Counter(
    "telemetry_delivery_success_total",
    "Total number of successfully delivered telemetry messages",
)

TELEMETRY_DELIVERY_FAILED = Counter(
    "telemetry_delivery_failed_total",
    "Total number of telemetry messages that failed delivery",
)

# --- Kafka delivery callback -------------------------------------------------

def delivery_report(err, msg):
    if err is not None:
        print(f"[ingest-service] Delivery failed: {err}")
        TELEMETRY_DELIVERY_FAILED.inc()
    else:
        print(f"[ingest-service] Delivered to {msg.topic()} [{msg.partition()}] offset {msg.offset()}")
        TELEMETRY_DELIVERY_SUCCESS.inc()

# --- Main loop ---------------------------------------------------------------

def main():
    producer_conf = {"bootstrap.servers": KAFKA_BROKER}
    producer = Producer(producer_conf)

    print(f"[ingest-service] producing to {TELEMETRY_TOPIC} on {KAFKA_BROKER}")
    print(f"[ingest-service] exposing metrics on :{METRICS_PORT}/metrics")

    # Start Prometheus metrics HTTP server
    start_http_server(METRICS_PORT)

    while True:
        msg = TelemetryPoint(
            timestamp=datetime.utcnow(),
            satellite_id="SAT-001",
            subsystem="EPS",
            parameter="battery_voltage",
            value=3.5 + random() * 0.2,  # 3.5–3.7 V
            unit="V",
            status="OK",
        )

        # Count telemetry generation
        TELEMETRY_GENERATED.inc()
        
        producer.produce(
            TELEMETRY_TOPIC,
            value=msg.model_dump_json().encode("utf-8"),
            callback=delivery_report,
        )
        producer.poll(0)
        time.sleep(1)


if __name__ == "__main__":
    main()
